<?php

global $parGeraTransf;
echo
"<table class='tabFormulario' >",
	$this->Cabecalhos( [ "Dados gerais", "FormCab alinhaMeio", "3" ] ),
	$this->Pedir( "Emissão",
		[ "", Emissao,
		[ brHtml(4) . "Vencimento ", Vencimento,
		[ brHtml(4) . "Valor ", Valor ] ] ] ),
"</table>",
"<br>",
"<table class='tabFormulario'>",
	$this->Cabecalhos( [ "Dados do débito", "FormCab alinhaMeio", "3" ] ),
	$this->Pedir( "Fornecedor", ForneDB ),
	$this->Pedir( "Conta corrente", CCorDB ),
   $this->Pedir( "Plano de contas",
      [ "", SubPlaDB_Plano_CodPlano,
      [ brHtml(2), SubPlaDB_Plano_Plano,
      [ "", SubPlaDB_Plano ] ] ] ),
   $this->Pedir( " ",
      [ "", SubPlaDB_Codigo,
      [ brHtml(2), SubPlaDB_Nome,
      [ "", SubPlaDB ] ] ] ),
	$this->Pedir( "Histórico", HistDB ),
	$this->Pedir( "Formas: Cobrança",
		[ "", TFCobraDB,
		[ brHtml(4) . "Pagamento ", TFPagtoDB,
		[ brHtml(4) . "Detalhe ", TDetPgDB ] ] ] ),
"</table>",
"<br>",
"<table class='tabFormulario'>",
	$this->Cabecalhos( [ "Dados do crédito", "FormCab alinhaMeio", "3" ] ),
	$this->Pedir( "Fornecedor", ForneCR ),
	$this->Pedir( "Conta corrente", CCorCR ),
   $this->Pedir( "Plano de contas",
      [ "", SubPlaCR_Plano_CodPlano,
      [ brHtml(2), SubPlaCR_Plano_Plano,
      [ "", SubPlaCR_Plano ] ] ] ),
   $this->Pedir( " ",
      [ "", SubPlaCR_Codigo,
      [ brHtml(2), SubPlaCR_Nome,
      [ "", SubPlaCR ] ] ] ),

	$this->Pedir( "Histórico", HistCR ),
	$this->Pedir( "Formas: Cobrança",
		[ "", TFCobraCR,
		[ brHtml(4) . "Pagamento ", TFPagtoCR,
		[ brHtml(4) . "Detalhe ", TDetPgCR ] ] ] ),
"</table>";
