<?php

echo
"<table class='tabFormulario'>",
	$this->Pedir( "Clínica", Clinica ),
   $this->Pedir( "Fornecedor" ),
   $this->Pedir( "Paciente", Pessoa_Nome ),
   $this->Pedir( " ",
      [ "Celular ", Pessoa_NumCelular,
      [ "", Pessoa ] ] ),
   $this->Pedir( "Tipo",
      [ "", TPgRec,
      [ brHtml(4) . "Competência ", TCompete ] ] ),
   $this->Pedir( "Vencimento",
      [ "", Venc,
      [ brHtml(4) . "Antecipa? ", Antecipa ] ] ),
   $this->Pedir( "Valor",
      [ "", Valor,
      [ brHtml(4) . "Estimado? ", Estimado ] ] ),
   $this->Pedir( "Cobrança", TFCobra ),
   $this->Pedir( "Histórico", Historico ),
   $this->Pedir( "Plano de contas",
      [ "", SubPlano_Plano_CodPlano,
      [ brHtml(2), SubPlano_Plano_Plano,
      [ "", SubPlano_Plano ] ] ] ),
   $this->Pedir( " ",
      [ "", SubPlano_Codigo,
      [ brHtml(2), SubPlano_Nome,
      [ "", SubPlano ] ] ] ),
   $this->Pedir( "Ativa?", Ativo ),
"</table>";
